variables:
  - &node_image "node:14-alpine"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64,linux/arm64,linux/arm/v7"

pipeline:
  - name: Test and Build
    image: *node_image
    commands:
      - apk add --no-cache curl
      - npm install
      - npm start &
      - sleep 5 # wait for the server to start up
      - curl -s localhost:3000
    ports:
      - 3000:3000

  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

branches: [main]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
