variables:
  - &node_image "node:14-alpine"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64,linux/arm64,linux/arm/v7"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

pipeline:
  - name: Install Dependencies
    image: *node_image
    commands:
      - npm install

  - name: Lint
    image: *node_image
    commands:
      - npm run lint

  - name: Test
    image: *node_image
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: yasifystools
    commands:
      - npm test

  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

  - name: Deploy Pull Request
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

branches: [main]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
